version: "3.3"

services:
  backend:
    image: gerrome/java-react-crud_backend:1
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2    
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.jpa.hibernate.ddl-auto" : "update",
         "spring.datasource.url" : "jdbc:mysql://mysql:3306/mysql",
         "spring.datasource.username" : "$MYSQLDB_USER",
         "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
         "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"
      }' 
    depends_on:
      - mysql
  
  frontend:
    image: gerrome/java-react-crud_frontend:1
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend      
   
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:  
      - db:/var/lib/mysql
    

  nginx:
    image: gerrome/java-react-crud_nginx:1
    #build:
    #  context: ./nginx
   #   dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - frontend          

volumes:
  db:      
